Number 
    -> Integer
     | Double

Integer
    -> '0-9'+

Double
    -> ...

Symbol
    -> Alpha ( Alnum | '-')*

Boolean
    -> '#t'
     | '#f'

List
    -> '(' Element * ')'

Element
    -> Integer
     | Symbol
     | Operator
     | Boolean
     | Function

Operator

Function
    -> '(' 'lambda' List List ')'
